@startuml

user -> frontend: pressMoveDotButton(direction)

alt direction == up
MovementButtons -> Controller: controller.moveDotUp()
else direction == down
MovementButtons -> Controller: controller.moveDotDown()
else direction == left
MovementButtons -> Controller: controller.moveDotLeft()
else direction == right
MovementButtons -> Controller: controller.moveDotRight()
end

Controller -> BackendCommunicator: sendMoveDotRequest(direction: DotMovementDirections)
frontend -> backend : {HTTP PATCH, /moveDot}
frontend <-- backend : { HTTP OK 200 } 

@enduml