@startuml

Index -> BackendCommunicator**: BackendCommunicator(ip, port)
Index <-- BackendCommunicator:  backendCommunicator

Index -> DotPosition**: DotPosition()
Index <-- BackendCommunicator: dotPosition

Index -> Controller**: Controller(backendCommunicator, dotPosition)
Index -> Controller: pollForCurrentDotPosition(100 : milliseconds)

@enduml