@startuml

user->browser: openPage www.myapp.com
browser -> httpServer: {HTTP GET /}
browser <-- httpServer: {HTTP 200 OK, ..., myAppFrontend}
user <-- browser: MyAppFrontend

loop every 100ms
    frontend -> backend: {HTTP GET /dotPosition}
    frontend <-- backend: {HTTP 200 OK, { x: xValue, y: yValue }} 
end

user -> frontend: pressMoveDotButton(direction);
frontend -> backend: {HTTP PATCH /moveDot, direction}

frontend <-- backend: {HTTP OK 200}
user <-- frontend: dot movement in specified direction;
@enduml